version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/log/project_logs
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - loki

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - loki
    logging:
      driver: json-file
      options:
         tag: "{{.Name}}"

  database:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - loki
    logging:
      driver: json-file
      options:
         tag: "{{.Name}}"

  live-app:
    image: python:3.9-slim
    ports:
      - "8000:8000"
    volumes:
      - ./app.py:/app.py
    command: python /app.py
    restart: always
    networks:
      - loki
    logging:
      driver: json-file
      options:
         tag: "{{.Name}}"

